version: 2
updates:
  - package-ecosystem: pip
    directory: /.github
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directories:
      - /keysas-admin
      - /keysas-firewall/tray-app
      - /keysas-frontend
    schedule:
      interval: daily
    # Disable version updates for npm dependencies, only open PRs for security updates
    open-pull-requests-limit: 0

  - package-ecosystem: cargo
    directories:
      - '**/Cargo.toml'
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
