version: 2
updates:
  - package-ecosystem: pip
    directory: /.github
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /keysas-admin
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /keysas-firewall/tray-app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /keysas-frontend
    schedule:
      interval: daily
