version: 2
updates:
  - package-ecosystem: pip
    directory: /.github
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directories:
      - /keysas-admin
      - /keysas-firewall/tray-app
      - /keysas-frontend
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-non-major-dependencies:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directories:
      - /keysas-firewall/daemon
      - /keysas-core
      - /keysas-backend
      - /keysas-firewall/libmailslot
      - /keysas_lib
      - /keysas-firewall/tray-app/src-tauri
      - /keysas-io
      - /keysas-sign
      - /keysas-admin/src-tauri
      - /keysas-fido
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
